# These are supported funding model platforms

github: [manjericao]
patreon: # manjericao
open_collective: # manjericao
ko_fi: # manjericao
tidelift: # npm/archunit-ts
custom: ['https://manjericao.io/sponsor']
